apiVersion: v1
kind: Service 
metadata:
  name: nginx-service1
spec:
  # Exponer el servicio en un puerto estático en cada nodo
  # para que podamos acceder al servicio desde fuera del clúster
  type: NodePort

  # Cuando el nodo recibe una solicitud en el puerto estático (30163)
  # "seleccionar pods con la etiqueta 'app' configurada como 'my-nginx-replicaset'"
  # y reenviar la solicitud a uno de ellos
  selector:
    app: my-nginx-replicaset 

  ports:
    # Tres tipos de puertos para un servicio
    # nodePort: un puerto estático asignado a cada nodo
    # puerto: puerto expuesto internamente en el clúster
    # targetPort: el puerto del contenedor al que enviar solicitudes
    - nodePort: 30163
      port: 8080 
      targetPort: 80