apiVersion: v1
kind: Service 
metadata:
  name: nginx-service1
spec:
  type: LoadBalancer
  selector:
    app: my-nginx-replicaset
  ports:
    # Tres tipos de puertos para un servicio
    # nodePort: un puerto estático asignado a cada nodo
    # puerto: puerto expuesto internamente en el clúster
    # targetPort: el puerto del contenedor al que enviar solicitudes
    - port: 8080 
      targetPort: 80